default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: bola10
  host: localhost
  pool: 5

development:
  <<: *default
  database: reporter_development

test:
  <<: *default
  database: reporter_test

production:
  <<: *default
  database: reporter_production

